2024-03-05 18:34:06,929 INFO    MainThread:18860 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-03-05 18:34:06,930 INFO    MainThread:18860 [wandb_setup.py:_flush():76] Configure stats pid to 18860
2024-03-05 18:34:06,930 INFO    MainThread:18860 [wandb_setup.py:_flush():76] Loading settings from /Users/benjamin/.config/wandb/settings
2024-03-05 18:34:06,930 INFO    MainThread:18860 [wandb_setup.py:_flush():76] Loading settings from /Users/benjamin/code/signification-game/base_experiment/wandb/settings
2024-03-05 18:34:06,930 INFO    MainThread:18860 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-05 18:34:06,930 INFO    MainThread:18860 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-05 18:34:06,930 INFO    MainThread:18860 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'base_experiment/ippo_ff.py', 'program_abspath': '/Users/benjamin/code/signification-game/base_experiment/ippo_ff.py', 'program': '/Users/benjamin/code/signification-game/base_experiment/ippo_ff.py'}
2024-03-05 18:34:06,930 INFO    MainThread:18860 [wandb_init.py:_log_setup():526] Logging user logs to /Users/benjamin/code/signification-game/base_experiment/wandb/run-20240305_183406-58fypno0/logs/debug.log
2024-03-05 18:34:06,930 INFO    MainThread:18860 [wandb_init.py:_log_setup():527] Logging internal logs to /Users/benjamin/code/signification-game/base_experiment/wandb/run-20240305_183406-58fypno0/logs/debug-internal.log
2024-03-05 18:34:06,930 INFO    MainThread:18860 [wandb_init.py:init():566] calling init triggers
2024-03-05 18:34:06,930 INFO    MainThread:18860 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-05 18:34:06,930 INFO    MainThread:18860 [wandb_init.py:init():616] starting backend
2024-03-05 18:34:06,930 INFO    MainThread:18860 [wandb_init.py:init():620] setting up manager
2024-03-05 18:34:06,931 INFO    MainThread:18860 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-03-05 18:34:06,933 INFO    MainThread:18860 [wandb_init.py:init():628] backend started and connected
2024-03-05 18:34:06,939 INFO    MainThread:18860 [wandb_init.py:init():720] updated telemetry
2024-03-05 18:34:06,957 INFO    MainThread:18860 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-05 18:34:07,223 INFO    MainThread:18860 [wandb_run.py:_on_init():2262] communicating current version
2024-03-05 18:34:07,296 INFO    MainThread:18860 [wandb_run.py:_on_init():2271] got version response 
2024-03-05 18:34:07,296 INFO    MainThread:18860 [wandb_init.py:init():804] starting run threads in backend
2024-03-05 18:34:08,448 WARNING MainThread:18860 [wandb_init.py:init():1198] interrupted
Traceback (most recent call last):
  File "/Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 817, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/Users/benjamin/miniforge3/envs/siggame/lib/python3.9/threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/benjamin/miniforge3/envs/siggame/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-03-05 18:34:11,865 WARNING MsgRouterThr:18860 [router.py:message_loop():77] message_loop has been closed
