2024-03-05 18:07:33,468 INFO    MainThread:17521 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-03-05 18:07:33,469 INFO    MainThread:17521 [wandb_setup.py:_flush():76] Configure stats pid to 17521
2024-03-05 18:07:33,469 INFO    MainThread:17521 [wandb_setup.py:_flush():76] Loading settings from /Users/benjamin/.config/wandb/settings
2024-03-05 18:07:33,469 INFO    MainThread:17521 [wandb_setup.py:_flush():76] Loading settings from /Users/benjamin/code/signification-game/base_experiment/wandb/settings
2024-03-05 18:07:33,469 INFO    MainThread:17521 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-05 18:07:33,469 INFO    MainThread:17521 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-05 18:07:33,469 INFO    MainThread:17521 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'base_experiment/ippo_ff.py', 'program_abspath': '/Users/benjamin/code/signification-game/base_experiment/ippo_ff.py', 'program': '/Users/benjamin/code/signification-game/base_experiment/ippo_ff.py'}
2024-03-05 18:07:33,469 INFO    MainThread:17521 [wandb_init.py:_log_setup():524] Logging user logs to /Users/benjamin/code/signification-game/base_experiment/wandb/run-20240305_180733-9hwqxzy5/logs/debug.log
2024-03-05 18:07:33,469 INFO    MainThread:17521 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/benjamin/code/signification-game/base_experiment/wandb/run-20240305_180733-9hwqxzy5/logs/debug-internal.log
2024-03-05 18:07:33,469 INFO    MainThread:17521 [wandb_init.py:init():564] calling init triggers
2024-03-05 18:07:33,469 INFO    MainThread:17521 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'_metadata': ContainerMetadata(ref_type=typing.Any, object_type=<class 'dict'>, optional=True, key=None, flags={'struct': True}, flags_root=False, resolver_cache=defaultdict(<class 'dict'>, {'now': {('%Y-%m-%d',): '2024-03-05', ('%H-%M-%S',): '18-07-32'}}), key_type=typing.Any, element_type=typing.Any), '_parent': None, '_flags_cache': {'struct': True}, '_content': {'LR': 0.0005, 'NUM_ENVS': 3, 'NUM_STEPS': 360, 'TOTAL_TIMESTEPS': 100000.0, 'UPDATE_EPOCHS': 4, 'MINIBATCH_SIZE': 30, 'GAMMA': 0.99, 'GAE_LAMBDA': 0.95, 'CLIP_EPS': 0.2, 'ENT_COEF': 0.01, 'VF_COEF': 0.5, 'MAX_GRAD_NORM': 0.5, 'ENV_NAME': 'simple-sig-game', 'ENV_DATASET': 'mnist', 'ENV_KWARGS': {}, 'ANNEAL_LR': False, 'WANDB_MODE': 'online', 'ENTITY': '', 'PROJECT': 'signification-game'}}
2024-03-05 18:07:33,470 INFO    MainThread:17521 [wandb_init.py:init():614] starting backend
2024-03-05 18:07:33,470 INFO    MainThread:17521 [wandb_init.py:init():618] setting up manager
2024-03-05 18:07:33,471 INFO    MainThread:17521 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-03-05 18:07:33,474 INFO    MainThread:17521 [wandb_init.py:init():624] backend started and connected
2024-03-05 18:07:33,701 ERROR   MainThread:17521 [wandb_init.py:init():1198] error
Traceback (most recent call last):
  File "/Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 629, in init
    run = Run(
  File "/Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 566, in __init__
    self._init(
  File "/Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 698, in _init
    self._config._update(config, ignore_locked=True)
  File "/Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 177, in _update
    sanitized = self._sanitize_dict(
  File "/Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 237, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 255, in _sanitize
    val = json_friendly_val(val)
  File "/Users/benjamin/miniforge3/envs/siggame/lib/python3.9/site-packages/wandb/util.py", line 671, in json_friendly_val
    converted = asdict(val)
  File "/Users/benjamin/miniforge3/envs/siggame/lib/python3.9/dataclasses.py", line 1075, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/Users/benjamin/miniforge3/envs/siggame/lib/python3.9/dataclasses.py", line 1082, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/Users/benjamin/miniforge3/envs/siggame/lib/python3.9/dataclasses.py", line 1112, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: first argument must be callable or None
2024-03-05 18:07:34,994 WARNING MsgRouterThr:17521 [router.py:message_loop():77] message_loop has been closed
